src/MVC/Controllers/BookController.cs
using Library_Managment_System.Data;
using Library_Managment_System.Models.DTOs.Books;
using Library_Managment_System.Models.DTOs.Reviews;
using Library_Managment_System.Services.Books;
using Library_Managment_System.Services.Reviews;
using Library_Managment_System.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Library_Managment_System.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IReviewService _reviewService;
        private readonly ApplicationDbContext _cntx;

        public BookController(IBookService bookService, IReviewService reviewService, ApplicationDbContext context)
        {
            _bookService = bookService;
            _reviewService = reviewService;
            _cntx = context;
        }

        public async Task<IActionResult> Index(
            string title = null,
            string author = null,
            DateTime? publishedDate = null,
            int? currentPage = null,
            string orderBy = null,
            int? itemsPerPage = null,
            bool desc = false)
        {
            title = title ?? "";
            author = author ?? "";
            itemsPerPage = itemsPerPage ?? 5;
            publishedDate = publishedDate ?? DateTime.Now;

            ViewData["Author"] = author;
            ViewData["Title"] = title;
            ViewData["itemsPerPage"] = itemsPerPage;

            Expression<Func<BookViewModel, bool>> func = x => x.Title.Contains(title) && x.Author.Contains(author) && x.PublishedDate <= publishedDate;

            var books = await _bookService.GetBooksAsync(desc, itemsPerPage, currentPage, func);

            switch (orderBy)
            {
                case "Title":
                {
                    books.Items = desc ? books.Items.OrderByDescending(x => x.Title) : books.Items.OrderBy(x => x.Title);
                    break;
                }
                case "Author":
                {
                    books.Items = desc ? books.Items.OrderByDescending(x => x.Author) : books.Items.OrderBy(x => x.Author);
                    break;
                }
                case "PublishedDate":
                {
                    books.Items = desc ? books.Items.OrderByDescending(x => x.PublishedDate) : books.Items.OrderBy(x => x.PublishedDate);
                    break;
                }
            }
            
            if(books.Errors.Count > 0)
            {
                foreach(var error in books.Errors)
                {
                    ModelState.AddModelError("", error);
                }
            }

            return View(books);
        }

        [HttpGet]
        public async Task<IActionResult> Image(Guid id)
        {
            var image = await _cntx.Images.FirstOrDefaultAsync(x => x.Id == id);
            byte[] buffer = image.Bytes;
            var imageExtension = GetImageExtension(buffer);

            return File(buffer, $"image/{imageExtension}");
        }

        private string GetImageExtension(byte[] buffer)
        {
            Dictionary<string, List<byte[]>> fileSignature = new Dictionary<string, List<byte[]>>{
                { "jpeg", new List<byte[]>{
                        new byte[] { 0xFF, 0xD8, 0xFF, 0xE0 },
                        new byte[] { 0xFF, 0xD8, 0xFF, 0xE2 },
                        new byte[] { 0xFF, 0xD8, 0xFF, 0xE3 },
                    }
                },
                { "jpg", new List<byte[]>{
                        new byte[] { 0xFF, 0xD8, 0xFF, 0xE0 },
                        new byte[] { 0xFF, 0xD8, 0xFF, 0xE1 },
                        new byte[] { 0xFF, 0xD8, 0xFF, 0xE8 },
                    }
                },
                { "png", new List<byte[]>{
                        new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A}
                    }
                }
            };

            foreach(var key in fileSignature.Keys)
            {
                bool match = fileSignature[key].Any(x => x.SequenceEqual(buffer.Take(x.Length)));

                if (match) return key;
            }

            throw new FileLoadException("This is not an image");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateBook input)
        {
            if(ModelState.IsValid)
            {
                var result = await _bookService.CreateBookAsync(input, User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value);

                if(result.Success)
                {
                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error);
                }
            }

            return View();
        }

        public async Task<IActionResult> Details(Guid bookId)
        {
            var viewModel = await _bookService.BookDetailsAsync(bookId);

            if(viewModel == null)
            {
                return NotFound();
            }

            return View("Details", viewModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid bookId)
        {
            if (bookId == null)
            {
                return NotFound();
            }

            try
            {
                await _bookService.DeleteBookAsync(bookId);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid bookId)
        {
            var book = await _bookService.GetBookAsync(bookId);

            if(book == null)
            {
                return NotFound();
            }

            return View(new EditBook
            {
                Id = book.Id,
                Author = book.Author,
                Description = book.Description,
                CurrentImage = book.ImageId,
                Link = book.Link,
                Title = book.Title
            });
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(EditBook input)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var result = await _bookService.EditBookAsync(input);

                    if(result.Success)
                    {
                        return RedirectToAction("Details", new { bookId = input.Id });
                    }

                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError("", error);
                    }
                }
                catch(ArgumentNullException)
                {
                    return NotFound();
                }
            }

            return await Edit(input.Id);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddComment(CreateReview input)
        {
            if(ModelState.IsValid)
            {
                var errors = await _reviewService.CreateReview(input);

                if(errors == null)
                {
                    return RedirectToAction(nameof(Details), new { bookId = input.BookId });    
                }

                ModelState.AddModelError("", errors);
            }

            return await Details(input.BookId);
        }
    }
}

src/MVC/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_Managment_System.Data;
using Library_Managment_System.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace Library_Managment_System.Controllers
{
    public class EventController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Event
        public async Task<IActionResult> Index()
        {
            return View(await _context.Events.ToListAsync());
        }

        // GET: Event/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Event/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ID,Title,Time,Place")] Event @event)
        {
            if (ModelState.IsValid)
            {
                @event.ID = Guid.NewGuid();
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Event/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ID,Title,Time,Place")] Event @event)
        {
            if (id != @event.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Event/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var @event = await _context.Events.FindAsync(id);
            _context.Events.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(Guid id)
        {
            return _context.Events.Any(e => e.ID == id);
        }
    }
}

src/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library Managment System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library Managment System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Library Managment System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/MVC/Views/Shared/_MainComment.cshtml
@model CreateReview

<div>
    <form asp-action="AddComment" asp-controller="Book" method="post">
        <input type="hidden" asp-for="ReviewerId" />
        <input type="hidden" asp-for="BookId" />

        <div class="form-outline">
            <label class="form-label" asp-for="Comment"></label>
            <textarea asp-for="Comment" class="form-control"></textarea>
            <span asp-validation-for="Comment" class="text-danger"></span>
        </div>

        <div>
            <button type="submit" class="btn btn-success mt-3">Comment</button>
        </div>
    </form>
</div>